/*
SHALAND V5 PRODUCT CATALOGUE
Replace each affiliateUrl with your real affiliate link before launch.
You can add more product objects by copying the format below.
*/
const PRODUCTS=[
{id:1,name:"Sony WH-CH520 Wireless Headphones",category:"tech",bestFor:"Everyday audio",rating:4.6,price:"₹4,490",badge:"Popular Pick",image:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=85",description:"Sony wireless on-ear headphones with up to 50 hours of battery life, quick charging, multipoint connectivity and a customizable EQ.",affiliateUrl:"https://www.amazon.in/Sony-Bluetooth-Headphones-Multipoint-Connectivity/dp/B0BS1RT9S2?_encoding=UTF8&content-id=amzn1.sym.b8ef64e4-7181-4319-a588-8dcfc7285537&dib=eyJ2IjoiMSJ9.7RS3nEYZ-4IvmnJYiFPZlgMVIT_LqxB3Ert6o_ArWGyuNxLX9rD2CNfk9zQob8024aPK_5MomLBBhC0wjnNxrljuM9fxwvf_MXEbbiB44XECG7PBmuz5Y12gdy7uum_woyP-ScFvfAJmejViDbBajgb23Qa3EZ1i5gfkOvuFUWG6tYxlcaR0w6Maua87WFkXcVFLlZHtNMhqP0cdrSpDWw.o8VEaZpuJpJK8NrH8ToMvZab1GrwG9Yb3i_XZV0-F1s&dib_tag=se&pd_rd_r=60ba4553-c090-4385-978f-029f409bbd61&pd_rd_w=UKAqT&pd_rd_wg=vIh3A&qid=1788292002&sr=8-1&th=1&linkCode=ll2&tag=shaland-21&linkId=3067a9dc37b73fc832e30ffc13c9954a&ref_=as_li_ss_tl",pros:["Up to 50-hour battery","Multipoint connectivity","Quick charging","Customizable EQ"],cons:["On-ear design may not suit everyone"],verdict:"A practical Sony wireless headphone for everyday listening, commuting and casual use.",retailer:"Amazon"},
{id:2,name:"FitTrack Smart Watch",category:"fitness",bestFor:"Fitness tracking",rating:4.6,price:"₹7,499",badge:"Best Value",image:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=85",description:"A practical smartwatch for workouts and everyday notifications.",affiliateUrl:"https://www.amazon.in/Fire-Boltt-Transparent-Bluetooth-Assistant-Smartwatch/dp/B0GGHG9CWT?dib=eyJ2IjoiMSJ9.fXyicKwZZnK-C_Cvifk7UOiTSuW6MuJkNtDLv5m5G0FK4La9jyQGUkpA4HHFDMYH9YKzydJxWh-ur6DJsWCFeLoxacAtpZKmUzvWT2KEujPs3m4Xgmqv14CY_jrzAcUiM4nCYHsJl9JI9oEeRdkLKfb-T7rCIA1J31YxrxAdo_hPVH76ZvW44kCHe2klc-uUWoP4VKmyOAcMGQtH0f-FTAcrRgXxCnszdebgWyrKNco.CHXyqRNPwtQ0ywh6CUuN0krodGbtA0izvkRi4K-agMg&dib_tag=se&keywords=smart%2Bwatch&qid=1788294651&sr=8-8&th=1&linkCode=ll2&tag=shaland-21&linkId=4194bfbea19ae86cde2101a6bc1f546b&ref_=as_li_ss_tl",pros:["Useful tracking","Everyday notifications","Good value"],cons:["Battery depends on usage"],verdict:"A sensible everyday fitness pick for shoppers who want useful basics.",retailer:"Add retailer"},
{id:3,name:"GlowDesk Lamp",category:"home",bestFor:"Home office",rating:4.5,price:"₹4,099",badge:"Popular",image:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=85",description:"Minimal desk lighting for focused work and study.",affiliateUrl:"https://example.com/affiliate-3",pros:["Clean design","Desk-friendly","Simple controls"],cons:["Limited advanced features"],verdict:"A practical choice when you want a clean-looking desk lamp without complexity.",retailer:"Add retailer"},
{id:4,name:"AirFlow Earbuds",category:"tech",bestFor:"Everyday audio",rating:4.4,price:"₹4,999",badge:"Trending",image:"https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=1200&q=85",description:"Compact wireless earbuds designed for daily listening.",affiliateUrl:"https://example.com/affiliate-4",pros:["Compact","Portable","Easy everyday use"],cons:["Smaller controls"],verdict:"A convenient everyday option for people who prioritize portability.",retailer:"Add retailer"},
{id:5,name:"FlexFit Resistance Kit",category:"fitness",bestFor:"Home workouts",rating:4.7,price:"₹2,999",badge:"Budget Pick",image:"https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=1200&q=85",description:"Portable resistance equipment for simple home workouts.",affiliateUrl:"https://example.com/affiliate-5",pros:["Portable","Budget friendly","Versatile"],cons:["Technique matters"],verdict:"Great for simple home training when portability and price matter.",retailer:"Add retailer"},
{id:6,name:"Urban Everyday Backpack",category:"style",bestFor:"Daily carry",rating:4.5,price:"₹5,499",badge:"Editor's Pick",image:"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=85",description:"Clean everyday backpack with practical organization.",affiliateUrl:"https://example.com/affiliate-6",pros:["Useful organization","Clean look","Everyday friendly"],cons:["Check size before ordering"],verdict:"A versatile daily-carry choice with a clean, practical design.",retailer:"Add retailer"}];
