/*
V4 PRODUCT DATABASE
Edit products here. This is your simple product catalogue.
Replace affiliateUrl with your real Amazon/Flipkart/other affiliate URL.
Replace image with your own image URL when possible.
*/
const PRODUCTS=[
{id:1,name:"Nova Pro Headphones",category:"tech",bestFor:"Premium audio",rating:4.8,price:"₹10,999",badge:"Editor's Pick",image:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1000&q=85",description:"Comfortable wireless headphones with immersive sound.",affiliateUrl:"https://example.com/affiliate-1",pros:["Comfortable design","Strong audio","Premium feel"],cons:["Price can vary"],verdict:"A strong all-round choice if audio quality and comfort are priorities."},
{id:2,name:"FitTrack Smart Watch",category:"fitness",bestFor:"Fitness tracking",rating:4.6,price:"₹7,499",badge:"Best Value",image:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=85",description:"A practical smartwatch for workouts and everyday notifications.",affiliateUrl:"https://example.com/affiliate-2",pros:["Useful tracking","Everyday notifications","Good value"],cons:["Battery depends on usage"],verdict:"A sensible everyday fitness pick for shoppers who want useful basics."},
{id:3,name:"GlowDesk Lamp",category:"home",bestFor:"Home office",rating:4.5,price:"₹4,099",badge:"Popular",image:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=85",description:"Minimal desk lighting for focused work and study.",affiliateUrl:"https://example.com/affiliate-3",pros:["Clean design","Desk-friendly","Simple controls"],cons:["Limited advanced features"],verdict:"A practical choice when you want a clean-looking desk lamp without complexity."},
{id:4,name:"AirFlow Earbuds",category:"tech",bestFor:"Everyday audio",rating:4.4,price:"₹4,999",badge:"Trending",image:"https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=1000&q=85",description:"Compact wireless earbuds designed for daily listening.",affiliateUrl:"https://example.com/affiliate-4",pros:["Compact","Portable","Easy everyday use"],cons:["Smaller controls"],verdict:"A convenient everyday option for people who prioritize portability."},
{id:5,name:"FlexFit Resistance Kit",category:"fitness",bestFor:"Home workouts",rating:4.7,price:"₹2,999",badge:"Budget Pick",image:"https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=1000&q=85",description:"Portable resistance equipment for simple home workouts.",affiliateUrl:"https://example.com/affiliate-5",pros:["Portable","Budget friendly","Versatile"],cons:["Technique matters"],verdict:"Great for simple home training when portability and price matter."},
{id:6,name:"Urban Everyday Backpack",category:"style",bestFor:"Daily carry",rating:4.5,price:"₹5,499",badge:"Editor's Pick",image:"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=85",description:"Clean everyday backpack with practical organization.",affiliateUrl:"https://example.com/affiliate-6",pros:["Useful organization","Clean look","Everyday friendly"],cons:["Check size before ordering"],verdict:"A versatile daily-carry choice with a clean, practical design."}];